# Generated by Django 5.2.7 on 2025-12-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(db_column='idevento', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='nomeevento', max_length=255, verbose_name='Nome do Evento')),
                ('data_inicio', models.DateField(db_column='datainicio', verbose_name='Data de Início')),
                ('data_fim', models.DateField(db_column='datafim', verbose_name='Data de Fim')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'gradeevento',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
