# Generated by Django 5.2.7 on 2025-12-26 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuracao_grade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Início da Grade')),
                ('data_fim', models.DateField(verbose_name='Fim da Grade')),
                ('grupo_economico_codigo', models.CharField(help_text='Código do fornecedor/grupo no ERP', max_length=50, verbose_name='Cód. Grupo Econômico')),
                ('grupo_economico_nome', models.CharField(max_length=255, verbose_name='Nome do Grupo Econômico')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('aberta', 'Em Aberto'), ('fechada', 'Fechada/Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Comprador Responsável')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='apuracao_grade.evento', verbose_name='Evento Comercial')),
            ],
            options={
                'verbose_name': 'Grade de Compra',
                'verbose_name_plural': 'Grades de Compras',
                'indexes': [models.Index(fields=['evento', 'comprador'], name='apuracao_gr_evento__268b71_idx'), models.Index(fields=['status'], name='apuracao_gr_status_fb33a3_idx')],
            },
        ),
    ]
