# Generated by Django 5.2.7 on 2025-12-29 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuracao_grade', '0002_alter_evento_atualizado_em_alter_evento_criado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_resumida', models.CharField(help_text='Ex: Suco Tang Diversos Sabores 25g', max_length=255, verbose_name='Descrição Resumida')),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('CX', 'Caixa'), ('FD', 'Fardo'), ('KG', 'Quilo'), ('TON', 'Tonelada')], default='UN', max_length=10)),
                ('volume_negociado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Volume Total Negociado')),
                ('custo_bruto', models.DecimalField(decimal_places=2, help_text='Custo com impostos', max_digits=10, verbose_name='Custo Bruto Unit.')),
                ('custo_liquido', models.DecimalField(decimal_places=2, help_text='Custo final sem impostos recuperáveis', max_digits=10, verbose_name='Custo Líquido Unit.')),
                ('verba_sell_in', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Verba Sell-In')),
                ('desconto_boleto', models.DecimalField(decimal_places=2, default=0, help_text='Informe o percentual (ex: 5.00 para 5%)', max_digits=5, verbose_name='Desconto Boleto (%)')),
            ],
        ),
        migrations.CreateModel(
            name='ItemGradeDistribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associado_id', models.IntegerField(verbose_name='ID Associado')),
                ('associado_nome', models.CharField(max_length=255)),
                ('percentual_participacao', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% Participação')),
                ('volume_compra_minima', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Volume Mínimo')),
            ],
            options={
                'verbose_name': 'Distribuição por Associado',
                'verbose_name_plural': 'Distribuições por Associados',
                'ordering': ['associado_nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemGradeSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=50, verbose_name='Cód. Produto (ERP)')),
                ('descricao_produto', models.CharField(max_length=255, verbose_name='Descrição (ERP)')),
                ('embalagem', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'SKU do Item',
            },
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-id'], 'verbose_name': 'Grade de Compra', 'verbose_name_plural': 'Grades de Compras'},
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='apuracao_gr_evento__268b71_idx',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='apuracao_gr_status_fb33a3_idx',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='comprador',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='grupo_economico_codigo',
        ),
        migrations.AddField(
            model_name='grade',
            name='comprador_responsavel',
            field=models.CharField(default='Sistema', max_length=150, verbose_name='Comprador Responsável'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='grupo_economico_id',
            field=models.CharField(default='Legado', max_length=50, verbose_name='Cód. Grupo Econômico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='grupo_economico_nome',
            field=models.CharField(max_length=255, verbose_name='Nome Grupo Econômico'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('em_analise', 'Em Análise'), ('aprovada', 'Aprovada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='rascunho', max_length=20),
        ),
        migrations.AddField(
            model_name='itemgrade',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='apuracao_grade.grade'),
        ),
        migrations.AddField(
            model_name='itemgradedistribuicao',
            name='item_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuicoes', to='apuracao_grade.itemgrade'),
        ),
        migrations.AddField(
            model_name='itemgradesku',
            name='item_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='apuracao_grade.itemgrade'),
        ),
        migrations.AlterUniqueTogether(
            name='itemgradesku',
            unique_together={('item_grade', 'codigo_produto')},
        ),
    ]
