# Generated by Django 5.2.7 on 2025-12-29 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuracao_grade', '0003_itemgrade_itemgradedistribuicao_itemgradesku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='grupo_economico_id',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='grupo_economico_nome',
        ),
        migrations.CreateModel(
            name='GradeGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_id', models.CharField(max_length=50, verbose_name='Cód. Grupo')),
                ('grupo_nome', models.CharField(max_length=255, verbose_name='Nome Grupo')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='apuracao_grade.grade')),
            ],
        ),
    ]
