# Generated by Django 5.2.7 on 2026-01-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuracao_grade', '0004_remove_grade_grupo_economico_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemgrade',
            name='quantidade_embalagem',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Ex: 12 (para caixa com 12 un)', max_digits=10, verbose_name='Qtd. na Embalagem'),
        ),
    ]
