# Generated by Django 5.2.7 on 2026-01-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuracao_grade', '0005_itemgrade_quantidade_embalagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemgradesku',
            options={'verbose_name': 'SKU do Item', 'verbose_name_plural': 'SKUs do Item'},
        ),
        migrations.AddField(
            model_name='itemgradedistribuicao',
            name='volume_fisico',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Volume convertido em unidades soltas para conferência', max_digits=12, verbose_name='Volume Físico (UN)'),
        ),
        migrations.AlterField(
            model_name='itemgradedistribuicao',
            name='volume_compra_minima',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Volume Mínimo (CX/FD)'),
        ),
        migrations.AlterUniqueTogether(
            name='itemgradedistribuicao',
            unique_together={('item_grade', 'associado_id')},
        ),
    ]
