# Generated by Django 5.2.7 on 2026-01-13 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuracao_grade', '0006_alter_itemgradesku_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='comprador',
            field=models.ForeignKey(blank=True, limit_choices_to={'perfil__eh_comprador': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_vinculadas', to=settings.AUTH_USER_MODEL, verbose_name='Comprador Responsável'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='comprador_responsavel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comprador (Antigo/Texto)'),
        ),
    ]
