# Generated by Django 5.2.7 on 2026-01-13 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuracao_grade', '0007_grade_comprador_alter_grade_comprador_responsavel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='comprador',
            field=models.ForeignKey(blank=True, limit_choices_to={'perfil__eh_comprador': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_comprador', to=settings.AUTH_USER_MODEL, verbose_name='Comprador Responsável'),
        ),
    ]
