# Generated by Django 5.2.7 on 2026-01-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_syncusuario_date_joined_syncusuario_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Associado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('status', models.CharField(default='ATIVO', max_length=20)),
            ],
            options={
                'verbose_name': 'Associado',
                'db_table': 'cadastro_associado',
                'managed': False,
            },
        ),
    ]
