# Generated by Django 5.2.7 on 2026-01-13 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_perfilusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syncusuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='syncusuario',
            name='user_permissions',
        ),
    ]
