"""
Django settings for supersync project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from google.cloud.sql.connector import Connector
import bcrypt
import dj_database_url
from dotenv import load_dotenv

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



caminho_credenciais = os.path.join(BASE_DIR, 'credenciais.json')

# Lógica Blindada:
if os.path.exists(caminho_credenciais):
    
    os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = caminho_credenciais
    
    
    GOOGLE_APPLICATION_CREDENTIALS = caminho_credenciais
    
    print(f"✅ Modo Local: Credenciais carregadas de {caminho_credenciais}")
else:

    GOOGLE_APPLICATION_CREDENTIALS = None 
    print("☁️ Modo Nuvem: Usando autenticação nativa do Google Cloud (ADC).")



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lo243ap+oyed(k!a*^#u!sv-bs@u3-yt^c=adyx$4^!($27i^#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptPasswordHasher', 
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
]

# Application definition

INSTALLED_APPS = [
    'utils',
    'apuracao_grade',
    'apuracao_contrato',
    'gcp_services',
    'usuarios',
    'contratos',
    'accounts',
    'dashboard',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'supersync.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Certifique-se de que esta linha existe
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'supersync.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# --- CONFIGURAÇÃO DE BANCO DE DADOS INTELIGENTE ---

# 1. Configuração Padrão (SQLite)
# Isso garante que o comando 'collectstatic' ou testes rodem sem erro mesmo sem banco
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# 2. Verifica se existe uma DATABASE_URL (Nuvem ou .env)
# O Cloud Run preenche isso automaticamente.
database_url = os.getenv('DATABASE_URL')

if database_url:
    # Se achou a URL (Nuvem), substitui a configuração do SQLite pelo Postgres
    DATABASES['default'] = dj_database_url.config(
        default=database_url,
        conn_max_age=600,
        ssl_require=True # Geralmente necessário para Cloud SQL
    )
else:
   
    if os.getenv('USAR_POSTGRES_LOCAL') == 'True':
         DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': 'sync',
                'USER': 'postgres',
                'PASSWORD': os.getenv('DB_PASSWORD', '13752738'), # Sua senha aqui
                'HOST': 'localhost',
                'PORT': '5432',
            }
        }


IS_CLOUD_RUN = os.getenv('K_SERVICE') is not None

if IS_CLOUD_RUN:
    # --- CONFIGURAÇÕES DE PRODUÇÃO (Nuvem) ---
    print("🔒 Modo Nuvem: Ativando segurança HTTPS")
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Lista de domínios confiáveis (Cloud Run)
    CSRF_TRUSTED_ORIGINS = [
        'https://supersync-teste-935499891935.southamerica-east1.run.app', 
        'https://supersync-teste.web.app/',
        'https://gestao.redesupermarket.com.br',
    ]
else:
    # --- CONFIGURAÇÕES LOCAIS (Seu PC) ---
    print("💻 Modo Local: Segurança HTTPS desativada para desenvolvimento")
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False


db_from_env = dj_database_url.config(conn_max_age=600)
DATABASES['default'].update(db_from_env)

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py
AUTH_USER_MODEL = 'usuarios.SyncUsuario'

# settings.py
AUTHENTICATION_BACKENDS = [
    #'usuarios.backends.PlainTextAuthBackend',
    'django.contrib.auth.backends.ModelBackend', # Mantém o backend padrão como fallback
]
