# Generated by Django 5.2.7 on 2025-12-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimFornecedor',
            fields=[
                ('seqpessoa', models.IntegerField(db_column='seqpessoa', primary_key=True, serialize=False)),
                ('nomerazao', models.CharField(db_column='NOMERAZAO', max_length=255)),
                ('fantasia', models.CharField(blank=True, db_column='FANTASIA', max_length=255, null=True)),
                ('nrocgccpf', models.CharField(db_column='NROCGCCPF', max_length=14)),
                ('digcgccpf', models.CharField(db_column='DIGCGCCPF', max_length=2)),
                ('cnpj_completo', models.CharField(db_column='cnpj_completo', max_length=18)),
                ('seqrede', models.IntegerField(db_column='SEQREDE')),
                ('nome_rede', models.CharField(blank=True, db_column='NOME_REDE', max_length=255, null=True)),
                ('seqloja', models.IntegerField(db_column='SEQLOJA')),
                ('seqassociado', models.IntegerField(blank=True, db_column='SEQASSOCIADO', null=True)),
                ('nomeassociado', models.CharField(blank=True, db_column='NOMEASSOCIADO', max_length=255, null=True)),
                ('tipfornecedor', models.CharField(blank=True, db_column='TIPFORNECEDOR', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Fornecedor (Dimensão)',
                'verbose_name_plural': 'Fornecedores (Dimensão)',
                'db_table': '"gold"."dim_fornecedor"',
                'managed': False,
            },
        ),
    ]
